# Generated by Django 4.2.10 on 2025-01-07 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimated_Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Air Ticket'), (2, 'Local Transport'), (3, 'Accomodation'), (4, 'Visa'), (5, 'Other'), (6, 'Per Diem')], default=1, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('number_unit_day', models.IntegerField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('travel_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.travel_request')),
            ],
        ),
    ]
