# Generated by Django 4.2.10 on 2025-01-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_estimated_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel_request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
