# Generated by Django 4.2.10 on 2025-01-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_travel_request_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_request',
            name='business',
            field=models.BooleanField(default=True),
        ),
    ]
