# Generated by Django 4.2.10 on 2025-01-08 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0005_travel_cost'),
        ('travel', '0004_alter_travel_request_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimated_cost',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_admin.travel_cost'),
        ),
    ]
