# Generated by Django 4.2.10 on 2025-01-09 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_estimated_cost_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.IntegerField(blank=True, null=True)),
                ('fund', models.IntegerField(blank=True, null=True)),
                ('lin_code', models.TextField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('travel_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.travel_request')),
            ],
        ),
    ]
