# Generated by Django 4.2.10 on 2025-01-09 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0006_fund_lin_code'),
        ('travel', '0006_finance_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_code',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_admin.fund'),
        ),
        migrations.AlterField(
            model_name='finance_code',
            name='lin_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_admin.lin_code'),
        ),
    ]
