# Generated by Django 4.2.10 on 2025-01-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_alter_finance_code_fund_alter_finance_code_lin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_code',
            name='dept',
            field=models.IntegerField(blank=True, default=23738, null=True),
        ),
    ]
