# Generated by Django 4.2.10 on 2025-01-10 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_program_travel_users_role'),
        ('app_admin', '0006_fund_lin_code'),
        ('travel', '0008_alter_finance_code_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('submission_status', models.BooleanField(default=True)),
                ('submission_note', models.TextField(blank=True, null=True)),
                ('budget_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_holder', to='program.traveluserroles')),
                ('finance_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_reviewer', to='program.traveluserroles')),
                ('security_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_reviewer', to='program.traveluserroles')),
                ('travel_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travel.travel_request')),
            ],
            options={
                'ordering': ('-submission_date',),
            },
        ),
        migrations.CreateModel(
            name='SubmitApproval_B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('approval_note', models.TextField(blank=True, null=True)),
                ('approval_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.approvalf_status')),
                ('submitrequest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travel.requestsubmit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.traveluserroles')),
            ],
        ),
    ]
