# Generated by Django 4.2.10 on 2025-01-11 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_program_travel_users_role'),
        ('app_admin', '0006_fund_lin_code'),
        ('travel', '0009_requestsubmit_submitapproval_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitApproval_S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('approval_note', models.TextField(blank=True, null=True)),
                ('approval_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.approvalf_status')),
                ('submitrequest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travel.requestsubmit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.traveluserroles')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitApproval_F',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('approval_note', models.TextField(blank=True, null=True)),
                ('approval_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.approvalf_status')),
                ('submitrequest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travel.requestsubmit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.traveluserroles')),
            ],
        ),
    ]
