# Generated by Django 4.2.10 on 2025-01-11 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0006_fund_lin_code'),
        ('travel', '0010_submitapproval_s_submitapproval_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitapproval_s',
            name='submission_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_admin.submission_status'),
        ),
    ]
