# Generated by Django 4.2.10 on 2025-01-11 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0006_fund_lin_code'),
        ('travel', '0011_submitapproval_s_submission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitapproval_s',
            name='submission_status',
        ),
        migrations.AddField(
            model_name='requestsubmit',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_admin.submission_status'),
        ),
        migrations.AlterField(
            model_name='requestsubmit',
            name='submission_status',
            field=models.BooleanField(default=False),
        ),
    ]
