# Generated by Django 4.2.10 on 2025-01-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_remove_requestsubmit_submission_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimated_cost',
            options={'ordering': ('type',)},
        ),
    ]
