# Generated by Django 4.2.10 on 2025-02-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partership',
            name='agreement_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partership',
            name='subAwar_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
