# Generated by Django 4.2.10 on 2025-02-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0002_partership_agreement_type_partership_subawar_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='partership',
            name='total_budget',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
