# Generated by Django 4.2.10 on 2025-02-24 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_program_travel_users_role'),
        ('portfolio', '0004_alter_portfolio_title_short'),
        ('partnership', '0003_partership_total_budget'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partership',
            new_name='Partnership',
        ),
    ]
