# Generated by Django 4.2.10 on 2024-02-20 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('working_title', models.CharField(blank=True, max_length=255, null=True)),
                ('fund_code', models.CharField(max_length=200, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('donor', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pcn_initiator', models.BooleanField(default=False)),
                ('is_pcn_technical_approver', models.BooleanField(default=False)),
                ('is_pcn_program_approver', models.BooleanField(default=False)),
                ('is_pcn_finance_approver', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='program.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='users_role',
            field=models.ManyToManyField(blank=True, through='program.UserRoles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_no', models.CharField(max_length=200)),
                ('indicator_title', models.CharField(max_length=255)),
                ('indicator_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Output'), (2, 'Outcome'), (3, 'Impact')], null=True)),
                ('indicator_unit', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Numeric'), (2, 'Percentage'), (3, 'Other')], null=True)),
                ('indicator_baseline', models.PositiveIntegerField(blank=True, null=True)),
                ('indicator_target_LoP', models.PositiveIntegerField(blank=True, null=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.program')),
            ],
        ),
    ]
