# Generated by Django 4.2.10 on 2024-02-22 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_fieldoffice'),
        ('program', '0002_implementationarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio'),
        ),
    ]
