# Generated by Django 4.2.10 on 2024-11-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_userroles_is_pacn_finance_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroles',
            name='apprval_budget_max_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userroles',
            name='apprval_budget_min_usd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
