# Generated by Django 4.2.10 on 2024-11-28 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_rename_apprval_budget_max_usd_userroles_approval_budget_max_usd_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='implementationarea',
            options={'ordering': ('-region',)},
        ),
    ]
