# Generated by Django 4.2.10 on 2025-01-10 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_profile_approval_budget_max_usd_and_more'),
        ('program', '0009_alter_implementationarea_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelUserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_initiator', models.BooleanField(default=False)),
                ('is_budget_holder', models.BooleanField(default=False)),
                ('is_finance_reviewer', models.BooleanField(default=False)),
                ('is_security_reviewer', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='program.program')),
            ],
        ),
    ]
