# Generated by Django 4.2.10 on 2025-01-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_profile_approval_budget_max_usd_and_more'),
        ('program', '0010_traveluserroles'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='travel_users_role',
            field=models.ManyToManyField(blank=True, through='program.TravelUserRoles', to='user.profile'),
        ),
    ]
