# Generated by Django 4.2.10 on 2024-03-05 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icnreportimpact',
            old_name='impact_pilot',
            new_name='actual_impact_pilot',
        ),
        migrations.RenameField(
            model_name='icnreportimpact',
            old_name='impact_scaleup',
            new_name='actual_impact_scaleup',
        ),
        migrations.AddField(
            model_name='activityreport',
            name='icnreport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report.icnreport'),
        ),
    ]
