# Generated by Django 4.2.10 on 2024-03-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_program_portfolio'),
        ('report', '0002_rename_impact_pilot_icnreportimpact_actual_impact_pilot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icnreport',
            name='iworeda',
            field=models.ManyToManyField(blank=True, related_name='program_rworedas', to='program.implementationarea'),
        ),
    ]
