# Generated by Django 4.2.10 on 2024-03-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_program_portfolio'),
        ('report', '0003_icnreport_iworeda'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='aworeda',
            field=models.ManyToManyField(blank=True, related_name='program_aworedas', to='program.implementationarea'),
        ),
    ]
