# Generated by Django 4.2.10 on 2024-04-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_icnreport_cs_currency_icnreport_mc_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityreport',
            old_name='actual_cost_sharing_budget_usd',
            new_name='actual_cost_sharing_budget',
        ),
        migrations.RenameField(
            model_name='activityreport',
            old_name='actual_mc_budget_usd',
            new_name='actual_mc_budget',
        ),
        migrations.RenameField(
            model_name='icnreport',
            old_name='actual_cost_sharing_budget_usd',
            new_name='actual_cost_sharing_budget',
        ),
        migrations.RenameField(
            model_name='icnreport',
            old_name='actual_mc_budget_usd',
            new_name='actual_mc_budget',
        ),
    ]
