# Generated by Django 4.2.10 on 2024-04-07 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0011_delete_icnreport'),
        ('report', '0006_rename_actual_cost_sharing_budget_usd_activityreport_actual_cost_sharing_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='cs_currency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'USD'), (2, 'ETB')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='mc_currency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'USD'), (2, 'ETB')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='icnreportimpact',
            name='impact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptnote.impact'),
        ),
    ]
