# Generated by Django 4.2.10 on 2024-09-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_alter_activityreportsubmit_submission_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreport',
            name='cs_currency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '$'), (2, 'Br')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='mc_currency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '$'), (2, 'Br')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='icnreport',
            name='cs_currency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '$'), (2, 'Br')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='icnreport',
            name='mc_currency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '$'), (2, 'Br')], default=1, null=True),
        ),
    ]
