# Generated by Django 4.2.10 on 2024-12-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_alter_icnreport_icn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreportimpact',
            name='actual_impact_pilot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityreportimpact',
            name='actual_impact_scaleup',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icnreportimpact',
            name='actual_impact_pilot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icnreportimpact',
            name='actual_impact_scaleup',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
