# Generated by Django 4.2.10 on 2024-04-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_approvalt_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvalf_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
