# Generated by Django 4.2.10 on 2024-02-22 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('address_url', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.portfolio_category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.portfolio_type')),
            ],
        ),
    ]
