# Generated by Django 4.2.10 on 2024-11-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_fieldoffice'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='title_short',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
