# Generated by Django 4.2.10 on 2024-11-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_title_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='title_short',
            field=models.CharField(max_length=100),
        ),
    ]
