# Generated by Django 4.2.10 on 2024-02-22 19:16

import conceptnote.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0002_fieldoffice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0002_implementationarea'),
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('proposed_start_date', models.DateField()),
                ('proposed_end_date', models.DateField()),
                ('final_report_due_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mc_budget_usd', models.FloatField(blank=True, null=True)),
                ('cost_sharing_budget_usd', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(choices=[(False, 'Draft'), (True, 'Submitted')], default=False, verbose_name='Status')),
                ('approval_status', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('alead_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='acns', to='portfolio.portfolio')),
                ('alead_co_agency', models.ManyToManyField(blank=True, related_name='aco_leads', to='portfolio.portfolio')),
                ('finance_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='afinance_lead', to='program.userroles')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, max_length=500, null=True, upload_to=conceptnote.models.path_and_rename)),
                ('ver', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('activity', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='conceptnote.activity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='auploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='ActivitySubmit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('submission_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Draft'), (2, 'Request Submitted')], default=2, null=True)),
                ('submission_note', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptnote.activity')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptnote.activitydocument')),
            ],
            options={
                'ordering': ('-submission_date',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, max_length=500, null=True, upload_to=conceptnote.models.path_and_rename)),
                ('ver', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='Icn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('proposed_start_date', models.DateField()),
                ('proposed_end_date', models.DateField()),
                ('final_report_due_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mc_budget_usd', models.FloatField(blank=True, null=True)),
                ('cost_sharing_budget_usd', models.FloatField(blank=True, null=True)),
                ('eniromental_impact', models.CharField(blank=True, max_length=255, null=True)),
                ('environmental_assessment_att', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('status', models.BooleanField(choices=[(False, 'Draft'), (True, 'Submitted')], default=False, verbose_name='Status')),
                ('approval_status', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('finance_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ifinance_lead', to='program.userroles')),
                ('ilead_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='icns', to='portfolio.portfolio')),
                ('ilead_co_agency', models.ManyToManyField(blank=True, related_name='co_leads', to='portfolio.portfolio')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='program.program')),
                ('program_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='iprogram_lead', to='program.userroles')),
                ('technical_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='itechnical_lead', to='program.userroles')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IcnSubmit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('submission_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Draft'), (2, 'Request Submitted')], default=2, null=True)),
                ('submission_note', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptnote.document')),
                ('icn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptnote.icn')),
            ],
            options={
                'ordering': ('-submission_date',),
            },
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('impact_pilot', models.IntegerField(blank=True, null=True)),
                ('impact_scaleup', models.IntegerField(blank=True, null=True)),
                ('icn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptnote.icn')),
                ('indicators', models.ManyToManyField(related_name='impacts', to='program.indicator')),
            ],
        ),
        migrations.CreateModel(
            name='IcnSubmitApproval_T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('approval_note', models.TextField(blank=True, null=True)),
                ('approval_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pending Review'), (2, 'Require Doc Update'), (3, 'Request Approved'), (4, 'Request Rejected')], default=1, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conceptnote.document')),
                ('submit_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conceptnote.icnsubmit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.userroles')),
            ],
        ),
        migrations.CreateModel(
            name='IcnSubmitApproval_P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('approval_note', models.TextField(blank=True, null=True)),
                ('approval_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pending Review'), (2, 'Require Doc Update'), (3, 'Request Approved'), (4, 'Request Rejected')], default=1, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conceptnote.document')),
                ('submit_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conceptnote.icnsubmit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.userroles')),
            ],
        ),
        migrations.CreateModel(
            name='IcnSubmitApproval_F',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('approval_note', models.TextField(blank=True, null=True)),
                ('approval_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pending Review'), (2, 'Require Doc Update'), (3, 'Request Approved'), (4, 'Request Rejected')], default=1, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conceptnote.document')),
                ('submit_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conceptnote.icnsubmit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.userroles')),
            ],
        ),
        migrations.CreateModel(
            name='IcnImplementationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptnote.icn')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_admin.region')),
                ('woreda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_admin.woreda')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_admin.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Icn_Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('approval_note', models.TextField(blank=True, null=True)),
                ('approval_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pending_Review'), (2, 'Require_Doc_Update'), (3, 'Approved'), (4, 'Rejected')], default=1, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conceptnote.document')),
                ('submit_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conceptnote.icnsubmit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.userroles')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='icn',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='conceptnote.icn'),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uploaded_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActivitySubmitApproval_T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('approval_note', models.TextField(blank=True, null=True)),
                ('approval_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pending Review'), (2, 'Require Doc Update'), (3, 'Request Approved'), (4, 'Request Rejected')], default=1, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conceptnote.activitydocument')),
                ('submit_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conceptnote.activitysubmit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.userroles')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySubmitApproval_P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('approval_note', models.TextField(blank=True, null=True)),
                ('approval_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pending Review'), (2, 'Require Doc Update'), (3, 'Request Approved'), (4, 'Request Rejected')], default=1, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conceptnote.activitydocument')),
                ('submit_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conceptnote.activitysubmit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.userroles')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySubmitApproval_F',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('approval_note', models.TextField(blank=True, null=True)),
                ('approval_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pending Review'), (2, 'Require Doc Update'), (3, 'Request Approved'), (4, 'Request Rejected')], default=1, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conceptnote.activitydocument')),
                ('submit_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conceptnote.activitysubmit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.userroles')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityImplementationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptnote.activity')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_admin.region')),
                ('woreda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_admin.woreda')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_admin.zone')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('impact_pilot', models.IntegerField(blank=True, null=True)),
                ('impact_scaleup', models.IntegerField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptnote.activity')),
                ('impact', models.ManyToManyField(related_name='activityimpacts', to='conceptnote.impact')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='icn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='conceptnote.icn'),
        ),
        migrations.AddField(
            model_name='activity',
            name='program_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aprogram_lead', to='program.userroles'),
        ),
        migrations.AddField(
            model_name='activity',
            name='technical_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='atechnical_lead', to='program.userroles'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
