# Generated by Django 4.2.10 on 2024-03-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_program_portfolio'),
        ('conceptnote', '0002_icn_iworeda'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='aworeda',
            field=models.ManyToManyField(blank=True, related_name='activity_woredas', to='program.implementationarea'),
        ),
    ]
