# Generated by Django 4.2.10 on 2024-03-17 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0004_icn_cs_currency_icn_mc_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icn',
            old_name='cost_sharing_budget_usd',
            new_name='cost_sharing_budget',
        ),
        migrations.RenameField(
            model_name='icn',
            old_name='mc_budget_usd',
            new_name='mc_budget',
        ),
    ]
