# Generated by Django 4.2.10 on 2024-04-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0008_activity_acn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icnsubmitapproval_f',
            name='approval_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pending Review'), (2, 'Require Doc Update'), (3, 'Request Endorsed'), (4, 'Request Rejected')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='icnsubmitapproval_t',
            name='approval_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Pending Review'), (2, 'Require Doc Update'), (3, 'Request Endorsed'), (4, 'Request Rejected')], default=1, null=True),
        ),
    ]
