# Generated by Django 4.2.10 on 2024-04-07 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0003_program_portfolio'),
        ('conceptnote', '0009_alter_icnsubmitapproval_f_approval_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcnReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_start_date', models.DateField()),
                ('actual_end_date', models.DateField()),
                ('actual_report_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mc_budget', models.FloatField(blank=True, null=True)),
                ('cost_sharing_budget', models.FloatField(blank=True, null=True)),
                ('mc_currency', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'USD'), (2, 'ETB')], default=1, null=True)),
                ('cs_currency', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'USD'), (2, 'ETB')], default=1, null=True)),
                ('status', models.BooleanField(choices=[(False, 'Draft'), (True, 'Submitted')], default=False, verbose_name='Status')),
                ('approval_status', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('finance_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_ifinance_lead', to='program.userroles')),
                ('icn', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_icn', to='conceptnote.icn')),
                ('iworeda', models.ManyToManyField(blank=True, related_name='actual_program_woredas', to='program.implementationarea')),
                ('program_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_iprogram_lead', to='program.userroles')),
                ('technical_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_itechnical_lead', to='program.userroles')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
