# Generated by Django 4.2.10 on 2024-04-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0010_icnreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IcnReport',
        ),
    ]
