# Generated by Django 4.2.10 on 2024-04-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0011_delete_icnreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDropdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_list', models.TextField()),
                ('approval_list', models.TextField()),
            ],
        ),
    ]
