# Generated by Django 4.2.10 on 2024-04-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0012_approvaldropdown'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovalDropdown',
        ),
    ]
