# Generated by Django 4.2.10 on 2024-04-09 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_approvalt_status'),
        ('conceptnote', '0013_delete_approvaldropdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icnsubmitapproval_t',
            name='approval_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.approvalt_status'),
        ),
    ]
