# Generated by Django 4.2.10 on 2024-04-09 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_approvalf_status'),
        ('conceptnote', '0014_alter_icnsubmitapproval_t_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icnsubmitapproval_f',
            name='approval_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.approvalt_status'),
        ),
        migrations.AlterField(
            model_name='icnsubmitapproval_p',
            name='approval_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.approvalf_status'),
        ),
    ]
