# Generated by Django 4.2.10 on 2024-04-10 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_submission_status'),
        ('conceptnote', '0015_alter_icnsubmitapproval_f_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icnsubmit',
            name='submission_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.submission_status'),
        ),
    ]
