# Generated by Django 4.2.10 on 2024-04-10 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0016_alter_icnsubmit_submission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icnsubmitapproval_p',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptnote.document'),
        ),
    ]
