# Generated by Django 4.2.10 on 2024-04-11 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0017_alter_icnsubmitapproval_p_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='icn',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='conceptnote.icn'),
        ),
    ]
