# Generated by Django 4.2.10 on 2024-04-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0018_alter_document_icn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='cost_sharing_budget_usd',
            new_name='cost_sharing_budget',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='mc_budget_usd',
            new_name='mc_budget',
        ),
        migrations.AddField(
            model_name='activity',
            name='cs_currency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'USD'), (2, 'ETB')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='mc_currency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'USD'), (2, 'ETB')], default=1, null=True),
        ),
    ]
