# Generated by Django 4.2.10 on 2024-04-14 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_submission_status'),
        ('conceptnote', '0019_rename_cost_sharing_budget_usd_activity_cost_sharing_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitysubmit',
            name='submission_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.submission_status'),
        ),
        migrations.AlterField(
            model_name='activitysubmitapproval_f',
            name='approval_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.approvalt_status'),
        ),
        migrations.AlterField(
            model_name='activitysubmitapproval_p',
            name='approval_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.approvalf_status'),
        ),
        migrations.AlterField(
            model_name='activitysubmitapproval_t',
            name='approval_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.approvalt_status'),
        ),
    ]
