# Generated by Django 4.2.10 on 2024-04-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0020_alter_activitysubmit_submission_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='acn_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
