# Generated by Django 4.2.10 on 2024-07-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0021_alter_activity_acn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='acn_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='icn',
            name='icn_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
