# Generated by Django 4.2.10 on 2024-09-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0022_alter_activity_acn_number_alter_icn_icn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='cs_currency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '$'), (2, 'Br')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='mc_currency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '$'), (2, 'Br')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='icn',
            name='cs_currency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '$'), (2, 'Br')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='icn',
            name='mc_currency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '$'), (2, 'Br')], default=1, null=True),
        ),
    ]
