# Generated by Django 4.2.10 on 2024-10-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0023_alter_activity_cs_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impact',
            name='unit',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Numeric'), (2, 'Percentage'), (3, 'Other')], null=True),
        ),
    ]
