# Generated by Django 4.2.10 on 2024-10-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0024_impact_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityimpact',
            name='unit',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Numeric'), (2, 'Percentage'), (3, 'Other')], null=True),
        ),
    ]
