# Generated by Django 4.2.10 on 2024-10-29 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_alter_implementationarea_unique_together'),
        ('conceptnote', '0025_activityimpact_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='icn',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='icn',
            name='mel_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='imel_lead', to='program.userroles'),
        ),
    ]
