# Generated by Django 4.2.10 on 2024-10-29 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_userroles_is_pacn_finance_approver_and_more'),
        ('conceptnote', '0026_alter_activity_options_alter_icn_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='mel_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='amel_lead', to='program.userroles'),
        ),
    ]
