# Generated by Django 4.2.10 on 2024-10-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0028_icnsubmitapproval_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='icn',
            name='approval_status_final',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
