# Generated by Django 4.2.10 on 2024-11-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_submission_status'),
        ('conceptnote', '0031_activitysubmitapproval_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='icn',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_admin.region'),
        ),
    ]
