# Generated by Django 4.2.10 on 2024-11-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0032_icn_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icn',
            name='region',
        ),
    ]
