# Generated by Django 4.2.10 on 2024-11-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_submission_status'),
        ('conceptnote', '0033_remove_icn_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='icn',
            name='iregion',
            field=models.ManyToManyField(blank=True, related_name='program_region', to='app_admin.region'),
        ),
    ]
