# Generated by Django 4.2.10 on 2024-11-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0034_icn_iregion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icn',
            name='iregion',
        ),
    ]
