# Generated by Django 4.2.10 on 2024-12-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0036_alter_activityimpact_impact_pilot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impact',
            name='impact_pilot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='impact',
            name='impact_scaleup',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
