# Generated by Django 4.2.10 on 2024-11-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approval_budget_max_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='approval_budget_min_usd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
