# Generated by Django 4.2.10 on 2025-01-20 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0006_fund_lin_code'),
        ('user', '0006_remove_profile_approval_budget_max_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emp_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='field_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ff', to='app_admin.fieldoffice'),
        ),
    ]
